### ISSUE TITLE
giveaway protection

### ISSUE THREAD

**Issue by Ietdown** [GoByeBye/DiscoRape#10]
it would be nice if you added some type of giveaway protection so the selfbot doesn't join giveaways for bans

**Comment by madebyzuoa** [comment]
theres literally no way of doing this lol. in my experince, people use the giveaway bot and jusdt type whatever to check for selfbots. theres no way of checking that.

**Comment by GoByeBye** [comment]
The only possible way I could think of doing anything like this is by setting a delay for when you join a giveaway to like 10-15 minutes but even then it won't stop you from joining the giveaway
