### ISSUE TITLE
crashing then trying to start

### ISSUE THREAD

**Issue by TomerGamerTV** [GoByeBye/DiscoRape#11]
![image](https://user-images.githubusercontent.com/44266242/97787531-8dfe0000-1bbb-11eb-8fe9-8c9b1c7db55f.png)
this is what i get

**Comment by scrazzz** [comment]
Read the error. It says `Improper token has been passed.`
Also make sure you're *not* using a bot token. This script is not for bots.

**Comment by GoByeBye** [comment]
Duped issue refer to this for solution

https://github.com/GoByeBye/DiscoRape/issues/4

**Comment by TomerGamerTV** [comment]
But what dose it mean? It showed the same then I tried the $neko command

**Comment by GoByeBye** [comment]
@TomerGamerTV It means you're not using a proper token
