### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by GamingTrooper71** [GoByeBye/DiscoRape#13]
When iterating over everyone in a guild, it can only fetch itself. I have also been having this problem, and know no solution. Do you know anything?

**Comment by zu0a** [comment]
That's because Discord's patched out fetching from selfbots, this means all mass-ban, mass-kick, mass-nick are now broken.

**Comment by GoByeBye** [comment]
This is a known issue since discord decided to take security semi seriously for once. Next patch will phase out nuking features
