### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Catterall** [GoByeBye/DiscoRape#14]
Suggestion to add list of commands in readme.md.

(GitHub needs to add a suggestions tab lol).

**Comment by GoByeBye** [comment]
I'd do it rn but due to work and school I haven't had time to work on DiscoRape

**Comment by GoByeBye** [comment]
If you want to fork this repo and add it yourself feel free to make a pull request and I'll add it in ;)

**Comment by Catterall** [comment]
Sure, I'll try.
