### ISSUE TITLE
I did everething that i needed to do and still i got this error code when trying to load it!

### ISSUE THREAD

**Issue by DiscordLetmeIn** [GoByeBye/DiscoRape#15]
`Cannot connect to host discord.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)')]`

**Comment by zu0a** [comment]
Go through the previous issues before making one, this was solved a while ago.
