### ISSUE TITLE
Missing discord formatting in anim.py

### ISSUE THREAD

**Issue by RadBoi** [GoByeBye/DiscoRape#2]
Command: $warning

Issue: Line 132 in anim.py "`SHUT-DOWN EXIT ERROR ¯\\(｡･益･)/¯", 

is missing a ` on the end

Markdown formatting on github fucks up the code if i write the fixed verson but there should be one at the start and one at the end but currently there's only one at the start

**Comment by GoByeBye** [comment]
Fixed in the latest commit
