### ISSUE TITLE
Module not found repl.it

### ISSUE THREAD

**Issue by ZenoMilk12** [GoByeBye/DiscoRape#3]
When i run it on repl.it itshows me this error:
![Screenshot_20200717-231417_Chrome.jpg](https://user-images.githubusercontent.com/63191158/87827280-4315e200-c883-11ea-8800-7665c3d4aa8d.jpg)

**Comment by GoByeBye** [comment]
Will fix in requirements.txt later today in the meanwhile you can fix this issue yourself by doing
`pip3 install colorama` then run bot again and it should run smoothly
