### ISSUE TITLE
Improper token has been passed.

### ISSUE THREAD

**Issue by ZenoMilk12** [GoByeBye/DiscoRape#4]
I m getting this error when I run start_bot.bat 
![Error](https://user-images.githubusercontent.com/63191158/87860116-6c964280-c943-11ea-99f0-22df2b915bb6.JPG)

**Comment by GoByeBye** [comment]
Try running it directly from cmd using
`python3 selfbot.py`
If you still get the same error it's your token that's wrong and nothing with the script

Tbh it's probably still your tokem that's wrong

**Comment by ZenoMilk12** [comment]
Yea it was expired bcs i changed my pass a long time ago and rechanged to my previous pass and my token changed.I used a token grabber to see my token and it worked.
